### ISSUE TITLE
[Bug]: Both default rulesets currently discard stress information

### ISSUE THREAD

**Issue by JoFrhwld** [Forced-Alignment-and-Vowel-Extraction/fave-recode#25]
### What happened?

It should be possible to retain stress somehow. Some of the rules are targeting vowels of any stress:

```yaml
- rule: eyf
  conditions: 
    - attribute: label
      relation: contains
      set: EY
    - attribute: fol.label
      relation: ==
      set: "#"
  return: eyF
```

To fix this, we may need an associated rule `action` or a more complex `return` behavior that allows regex replacement?

proposal:
```yaml
- rule: eyf
  conditions: 
    - attribute: label
      relation: contains
      set: EY
    - attribute: fol.label
      relation: ==
      set: "#"
  action:
    fun: re.sub
    args:
      - ".*(\\d)"
      - "eyF_\\1"
```

### What operating system are you using?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisbrickhouse** [comment]
For the moment I'm not a fan of this solution, but need to study the code a bit more before im firm either way.

Basically, I think we should limit the number of regex calls, and allowing (power) users to insert them at will seems like an anti-pattern, even more so if it's the default rules where we could optimize the parser for it. 

I think what we want is to have the parser expose particular attributes that the user can specify to construct an output, similar to python's format string. I'd imagine something like:

```YAML
- rule:
  ...
  return: ey{label.stress}F
```

Where `label.stress` is some internal variable given to the relevant parser group (maybe add a variable to conditions that allow naming the parser outputs for use in return?). This way we only need to parse once (the conditions) and can store those for use in return rather needing to parse again on return.

**Comment by JoFrhwld** [comment]
I'm about to swing back to this, and I think you're right. I think my initial hesitancy was that right now the system is very general purpose, so we couldn't assume CMU label input. But maybe adding an input labelset parser could work. By default, it would just be "string", but we could define a special parser for label sets that expose components like you have there for recoding.

**Comment by JoFrhwld** [comment]
See [this parser yaml for a sketch](https://github.com/Forced-Alignment-and-Vowel-Extraction/fave-recode/blob/25-bug-both-default-rulesets-currently-discard-stress-information/src/fave_recode/resources/cmu_parser.yml). I'm reusing the same rule schema, so that won't require additional code. 

My idea is that the `exposed_as` values will be set as attributes of each interval, so they could then be addressable within recoding rules as well. So, for example, the first block has rules for coding segments as vowels and consonants, with `exposed_as: "VC"`. A recoding scheme could then have a rule like

```yml
- rule: "haitus"
  conditions:
    - attribute: "VC"
      relation: "=="
      set: "vowel"
    - attribute: "fol.VC"
      relation: "=="
      set: "vowel"
  return: "haitus"
```
